### ISSUE TITLE
Suggestion: Add a licence

### ISSUE THREAD

**Issue by skornous** [ChibiBlasphem/themthem#1]
# Why
It's generally a good idea to have your code under a licence. I personally suggest the [MIT](https://choosealicense.com/licenses/mit/) one but you can check https://choosealicense.com to see if you prefer an other one.

**Comment by ChibiBlasphem** [comment]
Done in https://github.com/ChibiBlasphem/themthem/commit/6370aa37189e3ba3bf97a290e36f8b90e955b664
